### ISSUE TITLE
Switch to crc32

### ISSUE THREAD

**Issue by christianseel** [SEDAdigital/ChecksumFile#1]
I'd recommend to switch to crc32 checksums, which is considered faster and the specific use case for crc32 is to create a checksum for file integrity.

Also with crc32 we do not need to shorten our checksums.

```
$checksum = hash_file('crc32b', MODX_BASE_PATH.$file);
```

`crc32` vs `crc32b` is just a different table, while `crc32b` is used by PNG and ZIP.

**Comment by sebclemens** [comment]
Now integrated in release 0.2.0
